\mainmatter

# Introduction {#introduction .unnumbered}

Antimicrobial resistance (AMR) can be considered one of the most
critical health problems of the century. That is, microorganisms'
ability to grow despite exposure to substances designed to inhibit their
growth or kill them. In April 2014, the World Health Organization (WHO)
published its first global report on AMR surveillance
[@EditorialBoard2014]. Taking out of the darkness a common fear, a
possible post-antibiotic future in which common infections or minor
injuries can kill. Therefore, understanding the mechanisms of avoiding
antibiotic action is essential for producing knowledge and developing
strategies that reduce the generation of resistant bacteria.

Scientists have extensively studied the mechanisms that orchestrate the
growth and division of bacterial cells. Cells adapt their shape and
dimensions in response to variations in the intracellular and
extracellular environments by integrating information about the presence
of nutrients or harmful agents in the decision to grow or divide.
Filamentation is a process that occurs when rod-shaped cells stop
dividing but continue to grow, thus producing elongated cells
[@Wang2014; @Wang2014a; @jaimes-lizcano2014;
@justiceMorphologicalPlasticityBacterial2008]. Some cells can naturally
grow as filamentous, while others only do so under stressful conditions
[@cayron2020; @justiceFilamentationEscherichiaColi2006]. Here, we use
mathematical modeling and computational simulations to evaluate a toxic
agent's intracellular concentration as a function of cell length. We
show that filamentation can act as a strategy that promotes the
resilience of a bacterial population under stressful environmental
conditions.

Donec vitae turpis porttitor, tincidunt lorem ut, placerat ex. Ut
efficitur vel ante ut auctor. Morbi metus nisl, ullamcorper eu ante ac,
rutrum porttitor libero. Morbi rhoncus dui nulla, in tempus arcu
scelerisque eget. Proin rutrum ex at nibh faucibus luctus. Duis
scelerisque facilisis pulvinar. Interdum et malesuada fames ac ante
ipsum primis in faucibus. Fusce eu bibendum elit. Ut id sodales mauris.
Pellentesque in ipsum est.

Pellentesque neque dolor, vehicula ut porttitor eget, rhoncus id mi.
Suspendisse potenti. In hac habitasse platea dictumst. In sit amet felis
eget ante lacinia venenatis ac vitae turpis. Cras eget orci ut massa
egestas placerat vehicula vitae elit. Phasellus iaculis purus varius ex
pharetra, at faucibus est tristique. Sed vehicula venenatis leo, vitae
condimentum risus facilisis at. Praesent turpis tortor, finibus ut elit
in, vulputate ultricies tortor. Nam vel mauris non odio imperdiet
lobortis.
